// Generated by wxt
// Types for the #import virtual module
declare module '#imports' {
  export { browser, Browser } from 'wxt/browser';
  export { storage, StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage';
  export { useAppConfig } from 'wxt/utils/app-config';
  export { ContentScriptContext, WxtWindowEventMap } from 'wxt/utils/content-script-context';
  export { createIframeUi, IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe';
  export { createIntegratedUi, IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated';
  export { createShadowRootUi, ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root';
  export { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types';
  export { defineAppConfig, WxtAppConfig } from 'wxt/utils/define-app-config';
  export { defineBackground } from 'wxt/utils/define-background';
  export { defineContentScript } from 'wxt/utils/define-content-script';
  export { defineUnlistedScript } from 'wxt/utils/define-unlisted-script';
  export { defineWxtPlugin } from 'wxt/utils/define-wxt-plugin';
  export { injectScript, ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script';
  export { InvalidMatchPattern, MatchPattern } from 'wxt/utils/match-patterns';
  export { fakeBrowser } from 'wxt/testing';
  export { analytics } from '#analytics';
  export { default as ErrorBoundary } from '../src/components/ErrorBoundary';
  export { Toast, ToastType, ToastProps } from '../src/components/Toast';
  export { ToastContainer } from '../src/components/ToastContainer';
  export { useAuth, UseAuthReturn } from '../src/hooks/useAuth';
  export { useI18n, t } from '../src/hooks/useI18n';
  export { usePageTracking, PageTrackingOptions } from '../src/hooks/usePageTracking';
  export { ToastProvider, useToast, useToastHelpers } from '../src/hooks/useToast';
  export { animations, createBounceAnimation, getReducedMotion, getAnimation } from '../src/utils/animations';
  export { WHITE_LOGO_URL, X_SELECTORS, X_STYLE_TEXT, LINKEDIN_SELECTORS, LINKEDIN_STYLE_TEXT, YT_SELECTORS, YT_STYLE_TEXT, THREADS_SELECTORS, THREADS_STYLE_TEXT } from '../src/utils/constants';
  export { initLinkedInInjector } from '../src/utils/linkedinInjector';
  export { htmlToMarkdown, markdownToHtml, markdownToPlainTextPreview } from '../src/utils/markdownConverter';
  export { default as markdownRenderer } from '../src/utils/markdownRenderer';
  export { ExportPlatform, ExportPlatform, detectPlatform, isSupportedPlatform, getPlatformDisplayName, PlatformInfo } from '../src/utils/platformDetection';
  export { initRedditInjector } from '../src/utils/redditInjector';
  export { clipAndScrapCurrentPage, clipCurrentPageForStyle, initialScrapState, scrapStateHelpers, ScrapStatus, ScrapState } from '../src/utils/scrapHelper';
  export { initThreadsInjector } from '../src/utils/threadsInjector';
  export { translations, getTranslation, TranslationKey } from '../src/utils/translations';
  export { WebClipper, WebClipper, webClipper, quickClip, clipSelection, clipMinimal, PageMetadata, ScrapResult, ClipperOptions } from '../src/utils/webClipper';
  export { initXInjector } from '../src/utils/xInjector';
  export { initYouTubeInjector } from '../src/utils/youtubeInjector';
}
